### ISSUE TITLE
How to request permission for writing

### ISSUE THREAD

**Issue by somasekharkakarla** [ammarahm-ed/react-native-scoped-storage#12]
Hi, I am using scoped library. I am unable create file. It say you have no permission to create. Can you please how can I call permission. If possible please create a video tutorial on this.

**Comment by ammarahm-ed** [comment]
No you cannot. You have to atleast call `openDocumentTree` and persist the uri. Then later if you want to reuse the same uri, call `getPersistedUriPermissions` and save/read file. That's how scoped storage works on android.

First time
```js
let file = await ScopedStorage.openDocumentTree(true);
await ScopedStorage.writeFile(file.uri,"myfile.png");
```
Later
```js
let uri = await ScopedStorage.getPersistedUriPermissions();
await ScopedStorage.writeFile(uri,"myfile.png");
```
