### ISSUE TITLE
Android 11  - Unable to create directory in external storage

### ISSUE THREAD

**Issue by gkasireddy202** [ammarahm-ed/react-native-scoped-storage#16]
Hi Team,

'/storage/emulated/0'does not have permission to create directories - This error is occurred by using below code for creating the directory in external storage.

createDirectory=async()=>{

const path = `${RNFS.ExternalStorageDirectoryPath}`;
        try {
            const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE );
            if (granted == PermissionsAndroid.RESULTS.GRANTED) 
         {
                ScopedStorage.createDirectory(path, "TEST").then((obj) => {
                    alert(obj)
                })
                    .catch(error => {
                        console.log("ERROR" + error)
                    })

            } else {
                console.log('permission denied');
            }
        } catch (err) {
            console.warn(err);
        }

}

**Comment by ammarahm-ed** [comment]
You don't need any full storage permissions on android while using this library. So remove this: `.WRITE_EXTERNAL_STORAGE` from Android Manifest.

To take permissions use `openDocumentTree` method. Then use `createDirectory` on the returned directory uri.
