### ISSUE TITLE
How do I get a uri for application folder that the system provides?

### ISSUE THREAD

**Issue by CostachescuCristinel** [ammarahm-ed/react-native-scoped-storage#18]
The APIs in this lib require `uri`s to directories in order to write files. But there is no indication where to get any user folder uris, such as Documents, Downloads, or even an App directory where to write cache files.

Where can I get those?
I am looking for something similar to Expo's `FileSystem.cacheDirectory`.

**Comment by ammarahm-ed** [comment]
This is different than usual file management libraries. To get a directory, you need to call `openDocumentTree` and do operations on that uri.

**Comment by CostachescuCristinel** [comment]
So, there is no way to write some application cache files anywhere without asking the user to select a folder?

**Comment by ammarahm-ed** [comment]
@CostachescuCristinel  No. That is how scoped storage works. You can't publish apps to playstore with all files access from API 30 onwards.
