### ISSUE TITLE
When I delete the app, the saved file remains

### ISSUE THREAD

**Issue by rdtf1230** [ammarahm-ed/react-native-scoped-storage#19]
In scoped storage, I know that when the app is deleted, the files downloaded from the app are also deleted.
After i use this library to save my files, the files remain even i delete the app. Can you tell me what's happening?

this is what i wanted, but i want know why

**Comment by ammarahm-ed** [comment]
You cannot delete saved files on uninstall. User has the control of what is deleted from their device storage.
