### ISSUE TITLE
Getting access denied error.

### ISSUE THREAD

**Issue by niyasc** [ammarahm-ed/react-native-scoped-storage#20]
I'm trying to list the file names from a particular directory using the `listFiles` method. It is giving no permission error.

- Directory trying to read - /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/.Statuses

Error message
> /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/.Statuses do not have permission to read/write. Is there any other prerequisite I need to do to get the access?

**Comment by niyasc** [comment]
Just noticed the steps in https://github.com/ammarahm-ed/react-native-scoped-storage/issues/12. Will check and confirm if it is working. It should be in the README itself I think.

**Comment by brunofariasd** [comment]
> Just noticed the steps in #12. Will check and confirm if it is working. It should be in the README itself I think.

Did it work for you? 
I have the same problem here.

**Comment by ammarahm-ed** [comment]
> > Just noticed the steps in #12. Will check and confirm if it is working. It should be in the README itself I think.
> 
> Did it work for you? 
> I have the same problem here.

@brunofariasd it works, i am using this lib in a production app.

**Comment by brunofariasd** [comment]
> > > Just noticed the steps in #12. Will check and confirm if it is working. It should be in the README itself I think.
> > 
> > 
> > Did it work for you?
> > I have the same problem here.
> 
> @brunofariasd it works, i am using this lib in a production app.

Hello thx for this awesome lib, but can i use the absolute path
      example: /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/.Statuses, 

or do i have to use the uri returned from the function openDocumentTree?

**Comment by brunofariasd** [comment]
When I try read files with RNFetchBlob.lstat, i get this error:

[Error: failed to stat path `**/storage/emulated/0/Android/data/com.wpp.status_saver/files**/Android/media/com.whatsapp/Whatsapp/Media/.Statuses`

even i choose the correct path with openDocumentTree (/Android/media/com.whatsapp/Whatsapp/Media/.Statuses)
