### ISSUE TITLE
question : how ts works

### ISSUE THREAD

**Issue by Alirez14** [ammarahm-ed/react-native-scoped-storage#22]
Hi @ammarahm-ed 

I had this question in mind and I have struggled to find the answer but yet I could not 

the question I have is : 

how this package work is my js react native project although it contains only ts file and ts config but no ts package or compiler is available in the package.json + there is no compile process defined for it

and as I checked the node modules folder still I see only the ts file and no transformation file in the js 

please tell me how this package works in the js project

**Comment by ammarahm-ed** [comment]
Fixed in v1.9.2
