### ISSUE TITLE
Download file from API

### ISSUE THREAD

**Issue by gkasireddy202** [ammarahm-ed/react-native-scoped-storage#32]
Hi,

How to download files to internal storage from API.
I have an API for downloading files from SharePoint rest API.
Any method?

Thank you.

**Comment by vlxdisluv** [comment]
U can download through any convenient way but before you have to get access to directory by call the openDocumentTree method and after successful download call writeFile something like that: `const scopedStoragePath = await ScopedStorage.openDocumentTree(true);

const availableStoragePath = `${ExternalDirectoryPath}/${YOUR_DIRECTORY_NAME_IF_NEED}`;

const fileName = 'some.png';
const mime = 'image/png';

const androidOptions: RNFetchBlobConfig = {
  fileCache: true,
  addAndroidDownloads: {
    path: `${availableStoragePath}/${fileName}`,
  },
};

const downloadedFile = await RNFetchBlob.config(androidOptions).fetch('GET', remoteImageUrl);

await ScopedStorage.writeFile(scopedStoragePath.uri, fileName, mime, downloadedFile.data, 'base64');
`

**Comment by ammarahm-ed** [comment]
The above example is good enough. Thanks @vlxdisluv

**Comment by gkasireddy202** [comment]
@vlxdisluv  - Thanks for the reply.

I am getting error at const androidOptions: RNFetchBlobConfig = {
  fileCache: true,
  addAndroidDownloads: {
    path: '${availableStoragePath}/${fileName}',
  },
};

RNFetchBlobConfig : Type annotations can only be used in Typescript files.

How to send token along with the URL ?

**Comment by vlxdisluv** [comment]
@gkasireddy202 

it is perfectly described in [doc](https://github.com/joltup/rn-fetch-blob#download-example-fetch-files-that-need-authorization-token) for rn-fetch-blob

**Comment by ammarahm-ed** [comment]
> @vlxdisluv  - Thanks for the reply.
> 
> I am getting error at const androidOptions:
> 
> ```js
> const fetchConfig = {
>   fileCache: true,
>   addAndroidDownloads: {
>     path: `${availableStoragePath}/${fileName}`,
>   },
> };
> ```
> 
> RNFetchBlobConfig : Type annotations can only be used in Typescript files.
> 
> How to send token along with the URL ?
> 
> 

You are trying to assign fetch config to a typescript type & using it in a JS file which doesn't work.

I have made some edits.

**Comment by gkasireddy202** [comment]
@vlxdisluv - Thanks for replying.

Now it is working fine.
Can I use mime like below. From API response we don't get mime.

const mime = '*/*';
await ScopedStorage.writeFile(scopedStorageData.uri, fileName, mime, downloadedFile.base64(), 'base64');

**Comment by ammarahm-ed** [comment]
@gkasireddy202 You can I think. Something like */*. Although if you are requesting something from API, usually you should know what the file type is. You can also check the response headers to look for data type.

**Comment by gkasireddy202** [comment]
@ammarahm-ed  - Thanks for the reply. I will check the response header for the data type.
